drop table if exists board CASCADE;
create table board (
    id bigint generated by default as identity,
    writer varchar(10),
    title varchar(20),
    content text,
    createdAt varchar(20),
    primary key (id)
);